function [xFilled, report] = auto_fill(data, varargin)
%GAPFILL.AUTO_FILL Analyze, select strategy, and fill missing data.

    parser = inputParser;
    parser.addParameter("Time", [], @(x) isempty(x) || isvector(x));
    parser.addParameter("Methods", {"linear", "pchip", "makima"});
    parser.addParameter("NumReplicates", 6, @(x) isnumeric(x) && isscalar(x) && x >= 1);
    parser.addParameter("HoldoutFraction", 0.2, @(x) isnumeric(x) && isscalar(x) && x > 0 && x < 1);
    parser.addParameter("MinSegmentLength", 8, @(x) isnumeric(x) && isscalar(x) && x >= 3);
    parser.addParameter("MaxLag", 20, @(x) isnumeric(x) && isscalar(x) && x >= 1);
    parser.addParameter("MaxInterpolationGap", [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && x >= 0));
    parser.addParameter("MaxARGap", 200, @(x) isnumeric(x) && isscalar(x) && x >= 1);
    parser.addParameter("ARWindow", 150, @(x) isnumeric(x) && isscalar(x) && x >= 5);
    parser.addParameter("ARMaxOrder", 12, @(x) isnumeric(x) && isscalar(x) && x >= 1);
    parser.addParameter("Seed", 1, @(x) isnumeric(x) && isscalar(x));
    parser.addParameter("FillRemaining", false, @(x) islogical(x) && isscalar(x));
    parser.parse(varargin{:});
    opts = parser.Results;

    x = double(data(:));
    n = numel(x);
    if isempty(opts.Time)
        t = (1:n).';
    else
        t = double(opts.Time(:));
        if numel(t) ~= n
            error("gapfill:auto_fill:TimeSizeMismatch", ...
                "Time vector must have the same length as data.");
        end
    end

    evaluation = gapfill.evaluate_methods(x, ...
        "Time", t, ...
        "Methods", opts.Methods, ...
        "NumReplicates", opts.NumReplicates, ...
        "HoldoutFraction", opts.HoldoutFraction, ...
        "MinSegmentLength", opts.MinSegmentLength, ...
        "MaxLag", opts.MaxLag, ...
        "Seed", opts.Seed);

    bestMethod = evaluation.best_method;
    if isempty(opts.MaxInterpolationGap)
        maxInterpolationGap = gapfill.internal.choose_interpolation_gap( ...
            evaluation.profile.gap_lengths, ...
            evaluation.series_class, ...
            evaluation.profile, ...
            evaluation.backend);
    else
        maxInterpolationGap = opts.MaxInterpolationGap;
    end

    xInterp = gapfill.internal.interpolate_limited(t, x, bestMethod, maxInterpolationGap);
    xFilled = xInterp;

    if evaluation.backend.use_wavelet_context
        [xFilled, waveletReport] = gapfill.internal.wavelet_context_fill(xFilled, ...
            "Window", evaluation.backend.wavelet_window, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", min(opts.MaxARGap, evaluation.backend.wavelet_max_gap), ...
            "TopK", evaluation.backend.wavelet_top_k, ...
            "MaxScore", evaluation.backend.wavelet_score_cap, ...
            "ObservedMask", ~isnan(x));
    else
        waveletReport = struct('filled_gap_starts', zeros(0, 1), ...
            'filled_gap_ends', zeros(0, 1), 'filled_gap_lengths', zeros(0, 1), ...
            'best_scores', zeros(0, 1), 'best_candidate_starts', zeros(0, 1), ...
            'n_candidates_used', zeros(0, 1), 'n_filled_gaps', 0);
    end

    if evaluation.backend.use_multiscale_context
        [xFilled, multiscaleReport] = gapfill.internal.multiscale_context_fill(xFilled, ...
            "Window", evaluation.backend.multiscale_window, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", min(opts.MaxARGap, evaluation.backend.multiscale_max_gap), ...
            "TopK", evaluation.backend.multiscale_top_k, ...
            "MaxScore", evaluation.backend.multiscale_score_cap, ...
            "ObservedMask", ~isnan(x));
    else
        multiscaleReport = struct('filled_gap_starts', zeros(0, 1), ...
            'filled_gap_ends', zeros(0, 1), 'filled_gap_lengths', zeros(0, 1), ...
            'best_scores', zeros(0, 1), 'best_candidate_starts', zeros(0, 1), ...
            'n_candidates_used', zeros(0, 1), 'n_filled_gaps', 0);
    end

    if evaluation.backend.use_context_match
        [xFilled, contextMatchReport] = gapfill.internal.context_match_fill(xFilled, ...
            "Window", evaluation.backend.context_window, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", min(opts.MaxARGap, evaluation.backend.context_match_max_gap), ...
            "TopK", evaluation.backend.context_match_top_k, ...
            "MaxScore", evaluation.backend.context_match_score_cap, ...
            "ObservedMask", ~isnan(x));
    else
        contextMatchReport = struct('filled_gap_starts', zeros(0, 1), ...
            'filled_gap_ends', zeros(0, 1), 'filled_gap_lengths', zeros(0, 1), ...
            'best_scores', zeros(0, 1), 'best_candidate_starts', zeros(0, 1), ...
            'n_candidates_used', zeros(0, 1), 'n_filled_gaps', 0);
    end

    if evaluation.backend.use_roughness_bridge
        [xFilled, roughnessReport] = gapfill.internal.roughness_bridge_fill(xFilled, ...
            "Window", evaluation.backend.roughness_window, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", min(opts.MaxARGap, evaluation.backend.roughness_max_gap), ...
            "TopK", evaluation.backend.roughness_top_k, ...
            "MaxScore", evaluation.backend.roughness_score_cap, ...
            "ObservedMask", ~isnan(x));
    else
        roughnessReport = struct('filled_gap_starts', zeros(0, 1), ...
            'filled_gap_ends', zeros(0, 1), 'filled_gap_lengths', zeros(0, 1), ...
            'best_scores', zeros(0, 1), 'best_candidate_starts', zeros(0, 1), ...
            'n_candidates_used', zeros(0, 1), 'n_filled_gaps', 0);
    end

    if evaluation.backend.use_seasonal_template && ...
            ~isnan(evaluation.profile.stats.seasonality_period)
        seasonalMaxGap = min(opts.MaxARGap, max(maxInterpolationGap + 1, ...
            round(evaluation.profile.stats.seasonality_period * evaluation.backend.seasonal_gap_factor)));
        [xFilled, seasonalReport] = gapfill.internal.seasonal_template_fill(xFilled, ...
            "Time", t, ...
            "Period", evaluation.profile.stats.seasonality_period, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", seasonalMaxGap, ...
            "SeedMethod", bestMethod);
    else
        seasonalReport = struct('period', NaN, 'trend_window', NaN, ...
            'filled_gap_starts', zeros(0, 1), 'filled_gap_ends', zeros(0, 1), ...
            'filled_gap_lengths', zeros(0, 1), 'n_filled_gaps', 0);
    end

    if evaluation.backend.use_rolling_ar
        [xFilled, rollingARReport] = gapfill.internal.rolling_ar_fill(xFilled, ...
            "Window", opts.ARWindow, ...
            "MaxOrder", opts.ARMaxOrder, ...
            "MinGapLength", maxInterpolationGap + 1, ...
            "MaxGapLength", min(opts.MaxARGap, evaluation.backend.rolling_ar_max_gap));
    else
        rollingARReport = struct('filled_gap_starts', zeros(0, 1), ...
            'filled_gap_ends', zeros(0, 1), 'filled_gap_lengths', zeros(0, 1), ...
            'n_filled_gaps', 0);
    end

    [xFilled, arReport] = gapfill.internal.local_ar_fill(xFilled, ...
        "Window", opts.ARWindow, ...
        "MaxOrder", opts.ARMaxOrder, ...
        "MinGapLength", maxInterpolationGap + 1, ...
        "MaxGapLength", min(opts.MaxARGap, evaluation.backend.local_ar_max_gap), ...
        "Seed", opts.Seed);

    if opts.FillRemaining
        xFilled = gapfill.internal.interpolate_limited(t, xFilled, bestMethod, Inf);
    end

    report = struct;
    report.profile = evaluation.profile;
    report.evaluation = evaluation.results;
    report.strategy = struct( ...
        "series_class", evaluation.series_class, ...
        "series_class_confidence", evaluation.classification.confidence, ...
        "interpolation_method", bestMethod, ...
        "max_interpolation_gap", maxInterpolationGap, ...
        "max_ar_gap", opts.MaxARGap, ...
        "ar_window", opts.ARWindow, ...
        "ar_max_order", opts.ARMaxOrder, ...
        "seasonal_template_enabled", evaluation.backend.use_seasonal_template, ...
        "roughness_bridge_enabled", evaluation.backend.use_roughness_bridge, ...
        "wavelet_context_enabled", evaluation.backend.use_wavelet_context, ...
        "multiscale_context_enabled", evaluation.backend.use_multiscale_context, ...
        "context_match_enabled", evaluation.backend.use_context_match, ...
        "rolling_ar_enabled", evaluation.backend.use_rolling_ar, ...
        "fill_remaining", opts.FillRemaining);
    report.backend = evaluation.backend;
    report.roughness_bridge = roughnessReport;
    report.wavelet_context = waveletReport;
    report.multiscale_context = multiscaleReport;
    report.seasonal = seasonalReport;
    report.context_match = contextMatchReport;
    report.rolling_ar = rollingARReport;
    report.ar = arReport;
    report.n_missing_before = sum(isnan(x));
    report.n_missing_after = sum(isnan(xFilled));
    report.filled_fraction = 1 - report.n_missing_after / max(report.n_missing_before, 1);
end
